package com.aws.dynamodb.crudapirest.model;


import java.util.List;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;

import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

@Data
@AllArgsConstructor
@NoArgsConstructor
@Builder
@DynamoDBTable(tableName = "customers")

public class Customer {
    @DynamoDBHashKey
    @DynamoDBAutoGeneratedKey
    private String customerId;

    @DynamoDBAttribute
    private String name;

    @DynamoDBAttribute
    private String lastname;

    @DynamoDBAttribute
    private String email;

    @DynamoDBAttribute
    private int telephone;

    @DynamoDBAttribute
    private String orderDate;

    @DynamoDBAttribute
    private List<OrderItems> orderItems;

}
